### PR TITLE
Rewrite Package for 2.0.0

### LINKED ISSUE #2: [BUG] Parenthesised expressions scoped as tuples.
### Summary

Parenthesised expressions are being scoped as tuples rather than expressions. This also leads to contents of these expressions not being scoped correctly. For example:
```
   {{ (1 + 2) }}
// ^^^^^^^^^^^^^ text.html.basic meta.placeholder.jinja
// ^^ punctuation.definition.placeholder.begin.jinja
//    ^^^^^^^ meta.sequence.tuple.jinja
//    ^ punctuation.section.sequence.begin.jinja
//     ^ constant.numeric.integer.jinja
//         ^ constant.numeric.integer.jinja
//          ^ punctuation.section.sequence.end.jinja
//            ^^ punctuation.definition.placeholder.end.jinja

   {{ not (test and false) }}
// ^^^^^^^^^^^^^^^^^^^^^^^^^^ text.html.basic meta.placeholder.jinja
// ^^ punctuation.definition.placeholder.begin.jinja
//    ^^^ keyword.operator.word.jinja
//        ^^^^^^^^^^^^^^^^ meta.sequence.tuple.jinja
//        ^ punctuation.section.sequence.begin.jinja
//                       ^ punctuation.section.sequence.end.jinja
//                         ^^ punctuation.definition.placeholder.end.jinja
```
### Expected Behaviour

```
   {{ (1 + 2) }}
// ^^^^^^^^^^^^^ text.html.basic meta.placeholder.jinja
// ^^ punctuation.definition.placeholder.begin.jinja
//    ^^^^^^^ a sensible scope for parenthesised expressions
//    ^ punctuation.section.sequence.begin.jinja
//     ^ constant.numeric.integer.jinja
//       ^ keyword.operator.arithmetic.jinja
//         ^ constant.numeric.integer.jinja
//          ^ punctuation.section.sequence.end.jinja
//            ^^ punctuation.definition.placeholder.end.jinja

   {{ not (test and false) }}
// ^^^^^^^^^^^^^^^^^^^^^^^^^^ text.html.basic meta.placeholder.jinja
// ^^ punctuation.definition.placeholder.begin.jinja
//    ^^^ keyword.operator.word.jinja
//        ^ punctuation.section.sequence.begin.jinja
//         ^^^^ variable.other.jinja
//              ^^^ keyword.operator.word.jinja
//                  ^^^^^ constant.language.jinja
//                       ^ punctuation.section.sequence.end.jinja
//                         ^^ punctuation.definition.placeholder.end.jinja
```

### Actual Behaviour

See above.

### How to Reproduce

See above.

### Problematic Jinja2 template.

```
{{ (1 + 2) }}
{{ not (test and false) }}
```
### Environment

- Sublime Text build: 3211
- BetterJinja version: v1.0.0
- Operating System: macOS

### Additional context
Probably somehow making sure a comma is present before attempting to scope should fix this? Perhaps: https://github.com/sublimehq/Packages/blob/master/Python/Python.sublime-syntax#L925

I just spent a day working on an improved Jinja2 syntax, to then find out you've already done this 10 days prior! Should've done more research 😄

### LINKED ISSUE #4: [BUG] Tuple unpacking not scoped
### Summary

When doing parenthesised unpacking with an lvalue, inner names aren't scoped correctly.

### Expected Behaviour

It should work as if unparenthesised.

```
{% set (a, b) = test %}
//         ^ variable.other.jinja
//            ^ variable.other.jinja
```

### Actual Behaviour

```
   {% set (a, b) = test %}
//        ^^^^^^ text.html.basic meta.statement.jinja meta.sequence.tuple.jinja
```
No extra scopes are applied to the individual constituents.

### How to Reproduce

See above.

### Problematic Jinja2 template.

```
{% set (a, b) = test %} {# Contrived #}
{% for key, (v1, v2) in my_dict.items() %}  {# Realistic #}
```
### Environment

Same as before.

### Additional context
Might be related to #2 but I think that's caused by something else.

### LINKED ISSUE #7: Suggestion: Embedding into more languages + standalone syntax
Not a bug! A feature suggestion :)

Currently, BetterJinja only embeds the Jinja into HTML. I find that a bit of a limitation, since I use Jinja primarily for non-HTML things. It would therefore be cool if BetterJinja shipped with more embedding languages (JSON comes to mind, shell perhaps).

Additionally, regardless of whether more embedding languages are added, I think it'd be beneficial to split up syntax into a base Jinja syntax that can be used on any file, and depend on this base syntax in the embedding ones. For HTML, this would pretty much look like the following:
```yaml
- match: ""
      push: "Packages/HTML/HTML.sublime-syntax"
      with_prototype:
        - include: path/to/base.sublime-syntax#statement_blocks
        - ...
```
This is not too different from how it is already, but now it always loads the HTML by default. Any new embedding language could use the same template, this could probably be automated.

Benefits:
- The standalone syntax can be used on any file, not just HTML files. Of course, the HTML Jinja syntax can already be used on any file, but I can imagine there might be some parsing issues if Sublime tries to parse something that isn't HTML as HTML.
- The standalone file could be used by clients to create their own Jinja2-embedding syntax for the parser of their choice.
- More syntaxes = more features, and this can probably be automated.

Problems:
- How will all those different syntax definitions be distributed? Not everyone will want every language, and if there's 10s of syntax definitions, each for a different variant, it'll become confusing. On the other hand, distributing a mini-package for each is infeasible as well.

Would like to hear your thoughts on this. I'll probably soon experiment with this a bit. I'll also see whether I can use this syntax to create an improved Ansible syntax definition, since Ansible uses Jinja2 extensively in its YAML, but the expressions do not always have to be delimited by braces (certain strings are always parsed as Jinja2 templates). I've written a prototype syntax for Ansible recently, however, that uses my own Jinja2 syntax, so I'll see if I can migrate it.

### LINKED ISSUE #12: [BUG] bool is not highlighted when used in dict literal
### Summary

`false` and `true` are not highlighted when used in dict literal.

### Expected Behaviour

I expected `false` and `true` to be highlighted as they do when used in other places in the template.

### Actual Behaviour

`false` and `true` are not highlighted:
image

### How to Reproduce

1. Copy paste the Jinja2 template from below.
2. Set syntax to Jinja.

### Problematic Jinja2 template.

```jinja2
{{
    lookup('file', item, errors='ignore') or {}
    | from_json
    | combine({'openAtLogin': false})
    | to_json(sort_keys=true)
}}
```

### Environment

- Sublime Text build: 4126
- BetterJinja version: v1.0.0
- Operating System: Linux

### Additional context
[The old Jinja2 package](https://github.com/kudago/jinja2-tmbundle) highlighted this properly.

### LINKED ISSUE #13: Checklist for release of `v2.0.0`
### Description of your enhancement/feature request proposal.

This is basically an issue to track various stuff for the `v2.0.0` release. I had initially planned to do a `v1.2.0` with some syntax cleanups, but let's just do a direct `v2.0.0`.

- [x] Split the syntax into a core `Jinja` and then create `HTML (Jinja)`, `CSS (Jinja)` & `JavaScript (Jinja)` variants of it. This will resolve #7 and also supersede #10 without the need for `yaml-macros`.
- [ ] Create a `YAML (Jinja)` variant. This will be the only additional variant that will ship with `v2.0.0`. More can be added as & when users request it.
- [ ] Indentation tests
- [ ] Make the test suite more robust.

Other things that I might add in the future.

### LINKED ISSUE #14: `{% set foo = -1 %}` is scoped as invalid grammar
### Description of the bug

```
{% set foo = -1 %}
```

### Steps to reproduce

Just use the snippet above.

### Expected behavior

Not invalid grammar.

### Actual behavior

image

### BetterJinja version

1.1.0

### LINKED ISSUE #16: Support inline logic syntax
### Description of your enhancement/feature request proposal.

Jinja recently started [supporting](https://jinja.palletsprojects.com/en/3.0.x/templates/#line-statements) line statements, prepending line with configured symbol. In docs, `#` is set as used symbol for this.  
I find this quite useful, but I'm losing syntax highlighting from this plugin when I use this style.
Can line-statements be supported? Or is there an easy way to configure ST for this?
Also, can I set autocomplete to use this. I know I can create my sni

Thank you!

### Alternatives.

I use it without syntax highlight, and write code without help of autocomplete

### PR DESCRIPTION
**Pull request by deathaxe**
Fixes #2
Fixes #4
Fixes #7
Fixes #12
Resolves #13
Fixes #14
Fixes #16

Superseeds #10, #17

This PR is basically a complete rewrite of the whole package with every aspect being touched, while re-using as much of it as possible.

Supported template languages are: CSS, JavaScript, JSON, HTML, Markdown, XML, YAML

Syntax definitions extend bundled ones from ST4152+.

1. Package is re-structured to better organize all the supported syntaxes.

2. Snippets (and other resources) are indented using tabs as spaces don't play well with tab-indented target documents.

   E.g.: If snippets would be indented with spaces but committed to a document using tabs, spaces would remain and cause mixed indentation. Tabs are however converted to the correct number of spaces, when committed to a document using spaces for indentation.

3. a snippet for each tag is added so typing e.g. "if" and hitting tab expands to equivalent {% if ... %} tag.

4. Previous Jinja.sublime-syntax is mainly re-used but improved in various aspects by re-using patterns from Python syntax. It is renamed to "Text (Jinja)" and can be used for templates, which no dedicated syntax is shipped for (e.g.: LaTeX, ...).

---

Note: I'd also be happy to continue maintanance in _SublimeText_ org as it already collects various templating syntaxes and more. I'd also like to rename the repo to match the package name to avoid confusion.

It may cause some conflicts, but I'd suggest to

1. merge #20 and #21 first and release a 1.1.1
2. create a st4107 branch for the final 1.1.1 release
3. continue with master and update package_control_channel as this PR requires ST4152+

### CODE REVIEW

**Comment by UltraInstinct05** [comment]
@deathaxe First of all, thanks for all your work here. It's appreciated. 

Unfortunately my `$DAY_JOB` affords me little time to work on ST packages. I can offer you maintainer/admin rights for this repository (similar to how I provided @braver the rights for the `BetterTwig` repository in this organization) so that you can make new releases as you see fit.

**Comment by deathaxe** [comment]
Fully understandable. Maintainer rights would be fine as well.

**Comment by UltraInstinct05** [comment]
@deathaxe I have sent you a invite for maintainer access to this repository. Once you accept it, you should be able to merge PR's, triage issue and make releases.

**Comment by deathaxe** [comment]
OK, a 1.1.1 is released and some further tweaks to this branch have been made, including a rebase upon latest master.

Required changes to package_control_channel are pending at https://github.com/wbond/package_control_channel/pull/8918.

I'll leave this open for a while in case someone wants to take a closer look and/or make further suggestions to the current state as it is a rather big change in many aspects.

**Comment by FichteFoll** [comment]
Alternatively, we could also adopt this package under the @SublimeText org. (just throwing this in)

**Comment by deathaxe** [comment]
I like the idea of gathering widly used packages under SublimeText org as a kind of extension to sublimehq/Packages repo in general as well as grouping all LSP stuff under sublimelsp org.

Depends on whether Ashwin is ok to move the repo.

**Pull request merged**
